spring.application.name=IAM

# HTTPS
server.port=8443

# KeyStore
server.address=0.0.0.0
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password1!
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

# application.properties
spring.profiles.active=dev

# sap mock auth accout & password
sap.mock.auth=admin:secret

####### url ??
# SAP-MOCK BASE URL
#sap.mock.base-url=https://127.0.0.1:9443
sap.mock.base-url=https://10.20.110.178:9443
# ??? ??
sap.mock.employees-api=/sap/opu/odata/sap/EMPLOYEE_BASIC_SRV/Employees
# ??? ??
sap.mock.generate-api=/sap/opu/odata/sap/EMPLOYEE_BASIC_SRV/sap/mock/generate-employees
# ??? ??
sap.mock.add-api=/sap/opu/odata/sap/EMPLOYEE_BASIC_SRV/addEmployee

app.default-page-size=100

# SAP?? ?? json? ???? ??
sap.to.iam.fields=pernr,ename,orgeh,plans,email,begda,endda

